### PR TITLE
🛠 prettier + eslint (no additional rules)

### PR DESCRIPTION
**Pull request by alex-wilmer**
I believe prettier to be the bare minimum an open source projects needs to prevent multiple styles in the same project.

https://prettier.io/ is definitely the industry standard these days, and eslint is the industry standard for pointing inconsistencies while you're working.

The config file is very minimal and the options are selected to match your existing coding style.

### CODE REVIEW

**Comment by zander** [comment]
I talked with Ty on discord (highly recommended to join) about this and he regrets that he is not able to merge these until the weekend due to not having access to his github credentials until that time.
But I do understand that these cleanups are very welcome, and will be merged as soon as possible.

Thanks for your awesome work, always good to do some cleanups!

**Comment by ty-everett** [comment]
Was able to call someone to get 2FA key. Thanks for the PRs, it is appreciated and what this project needs.

**Comment by zander** [comment]
LOL, ok. Thanks for that :)

**Comment by alex-wilmer** [comment]
How do I join the discord channel? (I have it installed, I hardly ever use it)

**Comment by alex-wilmer** [comment]
sorry call me a discord noob but I'm still confused. this is what the "join" dialog looks like for me

image

**Comment by ty-everett** [comment]
In your browser try going to ambassador.cash

**Pull request merged**
